[tox]
requires =
    tox>=4
    tox-uv
env_list =
    py310
    py311
    py312
    py313
    py314
    lint
    type
install_loader = uv
install_pkg_loader = uv

[testenv]
package = wheel
change_dir = {toxinidir}
deps =
    -r requirements/requirements.txt
    -r requirements/requirements-dev.txt
commands =
    python -m pytest --cov --cov-report=term-missing -v {posargs}

[testenv:lint]
deps =
    ruff
commands =
    python -m ruff check src tests {posargs}

[testenv:type]
commands =
    python -m mypy {posargs}